# Generated by Django 5.0.1 on 2024-03-17 07:25

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='违禁词', max_length=255, verbose_name='违禁词')),
                ('type', models.IntegerField(choices=[('b', 'banned'), ('m', 'mask'), ('c', 'check')], default='b')),
            ],
            options={
                'verbose_name': '违禁词',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(default='8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', max_length=64, verbose_name='加密后的密码')),
                ('identity', models.CharField(choices=[('v', 'viewer'), ('r', 'report'), ('k', 'keyword'), ('b', 'banned')], default='v', max_length=1, verbose_name='身份')),
                ('gender', models.CharField(choices=[('w', 'woman'), ('m', 'man'), ('s', 'secret')], default='s', max_length=1, verbose_name='性别')),
                ('banned', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='uploads', verbose_name='路径')),
                ('file_name', models.TextField(blank=True, null=True, verbose_name='文件名')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '本地图片',
                'verbose_name_plural': '本地图片',
                'ordering': ['-created_time'],
                'unique_together': {('file_path',)},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('introduction', models.CharField(default='这个视频还没有简介哦', max_length=2000, verbose_name='视频简介')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('length', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='视频长度')),
                ('ViewCount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='播放量')),
                ('likeCount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('commentCount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('producer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='producer', to='like.user')),
                ('users', models.ManyToManyField(blank=True, to='like.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('contentId', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, '主键不可小于0')])),
                ('type', models.CharField(choices=[('c', 'comment'), ('b', 'bulletchat')], max_length=1)),
                ('reason', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('state', models.CharField(choices=[('p', 'pending'), ('a', 'approve'), ('r', 'reject')], default='p', max_length=1)),
                ('deal', models.CharField(max_length=100, null=True)),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent', to='like.user')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='like.user')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='like.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='like.user')),
                ('users', models.ManyToManyField(blank=True, related_name='like', to='like.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='like.video')),
            ],
        ),
        migrations.CreateModel(
            name='BulletChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('time', models.IntegerField(verbose_name='弹幕在视频中出现的时间')),
                ('level', models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0, '等级不可小于0'), django.core.validators.MaxValueValidator(5, '等级不可大于5')], verbose_name='屏蔽等级')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='like.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='like.video')),
            ],
            options={
                'verbose_name': '弹幕',
            },
        ),
    ]
