# Generated by Django 5.0.1 on 2024-03-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_alter_bannedword_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('v', 'viewer'), ('r', 'report'), ('k', 'keyword'), ('b', 'banned'), ('c', 'close')], default='v', max_length=1, verbose_name='身份'),
        ),
    ]
