# Generated by Django 5.0.1 on 2024-04-14 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_alter_user_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('frequency', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, '频数不可小于0')])),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='bulletchat',
            name='level',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0, '等级不可小于0'), django.core.validators.MaxValueValidator(4, '等级不可大于5')], verbose_name='屏蔽等级'),
        ),
    ]
