# Generated by Django 5.0.1 on 2024-04-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_wordfrequency_delete_image_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='video',
            name='videoName',
            field=models.CharField(default='SampleVideo_1280x720_10mb.mp4', max_length=100),
        ),
    ]
