# Generated by Django 5.0.1 on 2024-05-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0005_remove_user_avatar_video_videoname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='length',
        ),
        migrations.AlterField(
            model_name='bannedword',
            name='word',
            field=models.CharField(help_text='违禁词', max_length=255, unique=True, verbose_name='违禁词'),
        ),
    ]
