# Generated by Django 5.0.1 on 2024-05-11 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0006_remove_video_length_alter_bannedword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordfrequency',
            name='frequency',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, '频数不可小于0')]),
        ),
    ]
